### ISSUE TITLE
Failure on "Ensuring pip is installed" step

### ISSUE THREAD

**Issue by bnknkl** [macadmins/python#41]
Hi all, I'm trying to build this with `./build_python_framework_pkgs.zsh recommended` and it eventually errors out on the `Ensuring pip is installed...` step with this traceback:

```Ensuring pip is installed...
Traceback (most recent call last):
  File "/tmp/relocatable-python/relocatable-python-06b3052afe49c400aa4196f2aada15c0992e3725/make_relocatable_python_framework.py", line 108, in <module>
    main()
  File "/tmp/relocatable-python/relocatable-python-06b3052afe49c400aa4196f2aada15c0992e3725/make_relocatable_python_framework.py", line 99, in main
    without_pip=options.without_pip
  File "/private/tmp/relocatable-python/relocatable-python-06b3052afe49c400aa4196f2aada15c0992e3725/locallibs/install.py", line 103, in install_extras
    ensure_pip(framework_path, version)
  File "/private/tmp/relocatable-python/relocatable-python-06b3052afe49c400aa4196f2aada15c0992e3725/locallibs/install.py", line 35, in ensure_pip
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/ManagedFrameworks/Python/Python.framework/Versions/3.10/bin/python3.10', '-s', '-m', 'ensurepip']' returned non-zero exit status -9
Error running relocatable-python tool: 1
```

This is in a fresh virtual environment. Might be missing something obvious but would like a second set of eyes.

**Comment by pudquick** [comment]
Chiming in on this one - why is "--no-unsign" being set?

The error here is that install_name_tool is being used on the binary and invalidating the signature, which for M1 is a hard failure even for non-quarantined files on first run.

You -need- to ad-hoc resign these prior to their use. Why would you disable signature correction?

**Comment by erikng** [comment]
@pudquick We don't let the relocatable python do it, because our build script does what it does for us (and has some fixes for notarization).

To the OP: Any particular reason you are building this in your own? We signed and notarized this to be an easy install.

**Comment by erikng** [comment]
And I see now. This would be an M1 only issue, which we build on Intel machines for this, hence why we haven't seen this issue.

**Comment by pudquick** [comment]
Heard of the issue on Slack and can confirm it was an M1 at the time. Don't know why they were building it though.

**Comment by erikng** [comment]
Going to close this.
