### ISSUE TITLE
Will not build on latest versions of MacOS

### ISSUE THREAD

**Issue by DaeYi** [macadmins/python#46]
When calling the `./build_python_framework_pkgs.zsh` script without any changes, the following error occurs:

```
./build_python_framework_pkgs.zsh:125: /tmp/relocatable-python/relocatable-python-06b3052afe49c400aa4196f2aada15c0992e3725/make_relocatable_python_framework.py: bad interpreter: /usr/bin/python: no such file or directory
Error running relocatable-python tool: 127
```

After updating the .zsh script to change the `RP_SHA` variable to `RP_SHA="fb4dd9b024b249c71713f14d887f4bcea78aa8b0"` (latest version of relocatable-python), I get the following error during the relocatable-python build process:
```
Ensuring pip is installed...
Traceback (most recent call last):
  File "/tmp/relocatable-python/relocatable-python-fb4dd9b024b249c71713f14d887f4bcea78aa8b0/make_relocatable_python_framework.py", line 108, in <module>
    main()
  File "/tmp/relocatable-python/relocatable-python-fb4dd9b024b249c71713f14d887f4bcea78aa8b0/make_relocatable_python_framework.py", line 94, in main
    install_extras(
  File "/private/tmp/relocatable-python/relocatable-python-fb4dd9b024b249c71713f14d887f4bcea78aa8b0/locallibs/install.py", line 103, in install_extras
    ensure_pip(framework_path, version)
  File "/private/tmp/relocatable-python/relocatable-python-fb4dd9b024b249c71713f14d887f4bcea78aa8b0/locallibs/install.py", line 35, in ensure_pip
    subprocess.check_call(cmd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/ManagedFrameworks/Python/Python.framework/Versions/3.10/bin/python3.10', '-s', '-m', 'ensurepip']' died with <Signals.SIGKILL: 9>.
Error running relocatable-python tool: 1
```

I do not get this error when running relocatable-python on its own.

I'm happy to work on a pull request, if someone could point me in the right direction as to why this issue would occur when running within a script, and not occur while running on its own.

**Comment by erikng** [comment]
I'll be working on this with the latest hash.
